### ISSUE TITLE
Uncaught Error: Cannot find module 'stream'

### ISSUE THREAD

**Issue by xanderseren** [noraesae/react-render-html#1]
I am getting `Uncaught Error: Cannot find module 'stream'` when testing this out. Any ideas? Using react 0.14.7 and rendering the following...

`render() {return (<div>{renderHTML('<p>Hello World</p>')}</div>)}`

**Comment by noraesae** [comment]
We don't use `stream`, so it may be from other modules. Can you provide a minimal code or fiddle to reproduce the problem?

**Comment by noraesae** [comment]
Close for the inactivity.
