### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by siasjustin** [noraesae/react-render-html#11]
Hi, I am trying to use react-render-html but after installing it, once I include it in the file, using ..
import renderHTML from 'react-render-html';

I get the following error:
ERROR in ./~/react-attr-converter/map.json
Module parse failed: .../node_modules/react-attr-converter/map.json Unexpected token (2:10)
You may need an appropriate loader to handle this file type.

As soon as I comment out the import statement the error goes away. I am using webpack and below is the config file for that. Any idea what could be causing this?

configuration is as follows:

`var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'js/build');
var APP_DIR = path.resolve(__dirname, 'js');

var config = {
	entry: [
		APP_DIR + '/index.jsx',
		 // 'webpack/hot/only-dev-server'
	],
	output: {
		path: BUILD_DIR,
		filename: 'bundle.js'
	}, 
	// plugins: [
	// 	new webpack.HotModuleReplacementPlugin(),
	// ],
	module: {
		preLoaders: [
			{
				test: /\.jsx?$/,
				loader: 'eslint',
				exclude: /node_modules/
			}
		],
		loaders: [
			{
			 	test:/\.jsx?/,
				include : APP_DIR,
				loaders : ['babel'],
				exclude: /node_modules/
			}
			
		]
	},
	resolve: {
		extensions: ['', '.js', '.jsx'],
	}
};

module.exports = config;`

**Comment by bobbor** [comment]
@siasjustin you have to extend your config for babel to understand json

```bash
$ npm install json-loader --save-dev
```
then in webpack

```javascript
module.loaders : [
...
{
  // do not exclude node_modules, since map.json is in node_modules
  test: /\.json$/,
  loader: 'json'
}
...
]
```
and

```javascript
resolve.extensions: ['', '.js', '.jsx', '.json']
```

**Comment by siasjustin** [comment]
dude. thank you! new to jsx and webpack and now that you explain it, that makes total sense. very cool utility.

**Comment by khorolets** [comment]
@noraesae It'd be nice to include @bobbor's info in the README. @bobbor Thank you!

**Comment by noraesae** [comment]
It's rather a react-attr-converter issue, and not it doesn't use JSON.
