### ISSUE TITLE
[Question] Can I properly render a custom component?

### ISSUE THREAD

**Issue by khorolets** [noraesae/react-render-html#12]
Hi, everyone! @noraesae thank you for a great job!

I have a question from the subj. For example, my HTML comes to me from the backend and it contains something like that:

```html
<p>Hello, <Link to={"/people/bro"}>@bro</Link>!</p>
```

`<Link>` is the component from `react-router`. So the question is can I hope to render this component as it should be and expect that it would work properly? Also, can I render some project-specific components?

Thank you for your future answer!

**Comment by jnak** [comment]
I'm not the owner of the library, but it seems that the goal of this library takes HTML as input (not JSX) and converts it to a tree of react elements that you can then render.

**Comment by khorolets** [comment]
@jnak Thanks for your comment. I guess you're right, as I needed to render inner links, first of all, I came up with a workaround of catching `click` events.

**Comment by jnak** [comment]
No worries. You should close the ticket if you're done.

**Comment by jwalker14** [comment]
FYI, I just did something similar. I am pulling my content from a back and was trying to make the links coming in relative for react-router.

For instance my backend is wordpress sitting at admin.site.com and my frontend is react/redux/xyz:

This code might need some tweaking and I apologize for bad style as this is my first time posting some type of help.

`swap(obj, component){
		// instantiating a null node
		let c = null
		// if the obj matches type '<a>'
		if(obj.type == "a"){
			// check if domain is external ...

			// we now have the url and can parse it
			let url = new URL(obj.props.href)
			// if the host is the backend site
			if(url.host == 'fam.pica.is'){
				// we are dealing with an internal link
				url = url.pathname
				// we need to clone elements so clone the element and do what we need to.
				// attach the old object key and children to it
				// *** for react-router set the to element
				c = React.cloneElement(component, {to: url, key:obj.key}, obj.props.children)
				// return the new element
				return c
			}
		}
		// return the old one if we didn't to anything
		return obj
	}
	// trying to be general but may need some tweaking.
	// takes a string type
	// takes a renderHTML element list
	replaceType(type, list){
		// if the list is empty just return the list
		if(list.length == 0){
			// do nothing
			return list
		}
		// iterate through the list
		for (var i = list.length - 1; i >= 0; i--) {
			// for renderHTML we have two types string and object
			// for string we don't do anything it's just text or something else
			if(typeof list[i] == 'object'){
				// if it an object renderHTML has rendered a REACT element
				if(list[i].type == type){
					// if it's the type we are looking for
					// send it through the swap function
					list[i] = this.swap(list[i], <Link />)
				}
				// if this element has children then we need to repeat this on those children. recursive
				if(list[i].props.children != undefined && list[i].props.children.length > 0){
					// again we can't edit the props or children so just clone the element and call the replaceType on the children
					list[i] = React.cloneElement(list[i], list[i].props, this.replaceType(type, list[i].props.children))
				}
			}
		}

		// return the list changed
		return list
	}`
