### ISSUE TITLE
sometimes not rendering google ads same as dangerousinnerhtml

### ISSUE THREAD

**Issue by cinder92** [noraesae/react-render-html#16]
Hello i have this code

`renderHTML("<script async src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'></script><ins class='adsbygoogle' style='display: inline-block; width: 300px; height: 250px;' data-ad-client='ca-pub-8115515276052071' data-ad-slot='7807585453'></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>")`

but not always rendering.

**Comment by noraesae** [comment]
Script tags aren't properly rendered in React. Please refer to the following SO threads.

- https://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx
- https://stackoverflow.com/questions/31276926/how-to-add-script-tag-using-reactjs
