### ISSUE TITLE
Upgrade to react v15

### ISSUE THREAD

**Issue by scotchapman** [noraesae/react-render-html#2]
Are there any plans of upgrading this to use react v15?

**Comment by Wildhoney** [comment]
I'm using it with React `15.0.x` &mdash; what's the problem you're having?

**Comment by scotchapman** [comment]
Maybe it's a problem with the npm version I'm using (3.8.9). Instead of referencing react v15 it installs react v0.14.x as a dependency and uses that. I'm also using webpack and this adds almost 1mb (uncompressed) to the bundle.

**Comment by noraesae** [comment]
PR merged manually. Thanks!
