### ISSUE TITLE
0.2.0 breaks with uglify-js

### ISSUE THREAD

**Issue by fonsleenaars** [noraesae/react-render-html#20]
Using uglify-js in a webpack configuration with the 0.2.0 of react-render-html will throw this error:

`ERROR in 5a092131c105689b39df.js from UglifyJs
Invalid assignment [../~/react-render-html/index.js:17,0][5a092131c105689b39df.js:15118,48]`

I believe it's because there's ES6 syntax in the module, which uglify-js can't deal with.

**Comment by azwon** [comment]
Here's another error with UglifyJs and react-render-html:

static/js/main.2b538ea0.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/react-attr-converter/index.js:447,0]

**Comment by noraesae** [comment]
The ES2015 syntax used in the code is fat-arrow and const, and they are supported in all modern browsers. Actually, ES2015 itself is 100% supported in most of the modern browsers. If uglify-js cannot parse it, it's rather an issue of uglify-js. Please consider using [ES2015+ support of uglify-js](https://github.com/mishoo/UglifyJS2/tree/harmony) or ES2015-to-ES5 compilers.

**Comment by noraesae** [comment]
I met a situation where this actually matters. I may remove ES2015 syntax from code base.

**Comment by noraesae** [comment]
Fixed in v0.4.0. Thanks all!
