### ISSUE TITLE
Error in build process

### ISSUE THREAD

**Issue by schroeder71** [noraesae/react-render-html#23]
Hi,

today i want to try react-render-html. But if i try to build my project i get an error:

    ...
    react-scripts build

    Creating an optimized production build...
    Failed to compile.

    static/js/main.9eef3258.js from UglifyJs
    Unexpected token: name (isLastCharLower) [./~/react-render-html/~/camelcase/index.js:4,0][static/js/main.9eef3258.js:52368,5]
    ...

any idea?

**Comment by noraesae** [comment]
It's not specifically a problem of this library, but one of the camelcase package. 

https://github.com/sindresorhus/camelcase/commit/2296030d560d4620eb1773219686822eb9c322e3

I may consider revert to 3.0.

**Comment by noraesae** [comment]
Released v0.5.0 with the revert.
