### ISSUE TITLE
Error build Uglify JS

### ISSUE THREAD

**Issue by hazratgs** [noraesae/react-render-html#24]
Hi, an excellent plugin, but it's written in ES6 and when using UglifyJS an error occurs, can you recompile it on ES5?

**Comment by noraesae** [comment]
#20, #23 

ES2015 is reverted in the latest version. Please try with v0.5.0.

**Comment by kdenz** [comment]
0.5.0 works finally, ES2015 Totally broke my code on safari 9 and below
