### ISSUE TITLE
<iframe> not rendering

### ISSUE THREAD

**Issue by snamoah** [noraesae/react-render-html#25]
I'm trying to render an `iframe` into a react component. I make a remote call to get the iframe and then set it in a state. I then reference that in `render`. Please find the mock code below:

```javascript
import renderHtml from 'react-render-html';

class Test {
  constructor(props) {
    
  }

  componentDidMount() {
     remoteCall((e, r) => {
       if (r) {
         this.setState({
           iframe: r.iframe,
         });
       }
     });
  }

  render() {
    const iframe = this.state.iframe;
    return iframe ? (
       {renderHtml(iframe)}
    ) : null;
  }
}
```

**Comment by noraesae** [comment]
Iframe is not usual DOM element, so I guess it should be handled specially. react-render-html may not help in this case. I found alternative resources here:

- https://medium.com/@ebakhtarov/handling-of-iframes-in-react-f038be46ac24
- https://github.com/ryanseddon/react-frame-component

Please feel free to reopen if there is any further issue concerning react-render-html :)
