### ISSUE TITLE
Multiline render

### ISSUE THREAD

**Issue by Hongbo-Miao** [noraesae/react-render-html#26]
First thank you for the cool package!

For multiline
```js
renderHTML(`line 1
line 2`)
```
it now shows
```
line 1 line 2
```
instead of
```
line 1
line 2
```

The app I am building is reading emails. I checked other email clients, for same email, they all render as the second one.
Is there any way to render as the second one? Thanks!

**Comment by noraesae** [comment]
I think this is not an issue of react-render-html, as it's returning a result from [parse5](https://github.com/inikulin/parse5), an HTML parser, with newlines kept. The following code works without any problem.

```js
const { equal } = require('assert');
const { parseFragment: parseHTML } = require('parse5');
const renderHTML = require('react-render-html');

const input = `line 1
line 2`;

equal(parseHTML(input).childNodes[0].value, input); // parse5 keeps newlines
equal(renderHTML(input), input); // react-render-html also keeps newlines
```

May it be an issue of other components?

**FYI**: As you may already know, but newlines in HTML are just rendered as spaces in rendered pages. [ref](https://jsfiddle.net/mk1uxkpw/)

**Comment by Hongbo-Miao** [comment]
Thank you so much, @noraesae !

**Comment by Hongbo-Miao** [comment]
It was my mistake. There are two kinds of emails: text and html. I am using react-render-html to render text email. That is why. For text email, I should just show it directly.

**Comment by Hongbo-Miao** [comment]
For future people, there is an easy way to render plain text and keep the new line:

____
    
    .display-linebreak {
      white-space: pre-line;
    }

    <div className="display-linebreak"> 
       {plainText} 
    </div>
