### ISSUE TITLE
v0.5 breaking due to dependency on Camelcase?

### ISSUE THREAD

**Issue by clintonwoo** [noraesae/react-render-html#27]
Firstly I'd like to say great repo & package but I've got a problem when building with NextJS (I believe it uses webpack/uglifyjs)

Using version 0.1.5 everything is fine:
https://github.com/clintonwoo/hackernews-react-graphql/blob/2998bb504402b9bb88cea248a1b4cb035816d198/package.json#L55

Using version 0.5:
https://github.com/clintonwoo/hackernews-react-graphql/blob/42fb36a8bbc659ade2314ad2bd7bf660218feb65/package.json#L55

> Failed to build on /var/folders/p_/c4lmzrx10jxfv9409tl8_wv40000gn/T/b2c0ea43-7af8-46ce-a526-ab63df7ccf55
{ Error: bundles/pages/reply.js from UglifyJs
Unexpected token: name (isLastCharLower)

To reproduce:
```git clone https://github.com/clintonwoo/hackernews-react-graphql.git && cd hackernews-react-graphql```
Then revert the repo to abovementioned commits where v0.5 is not working and run:
```npm install && npm run build```

The current master branch is using the old 0.1.5 version due to getting this error. Also if I go into your package and comment out require('camelcase') my build succeeds and runs.

**Comment by noraesae** [comment]
I think it's an issue of which version of `camelcase` is installed. This kind of problem has been reported quite for a while, and I decided to just remove `camelcase` dependency.

The new version is released as v0.5.1.
