### ISSUE TITLE
Limit the css effect

### ISSUE THREAD

**Issue by Hongbo-Miao** [noraesae/react-render-html#28]
I am using react-render-html to render html email. Today I got an email which looks like this:
 
```
const mail = `<html lang="en">
 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <meta content="text/html; charset=utf-8">
 <style type="text/css">
 <!--
 body
 {font-size:12px}
 -->
 </style>
 </head>
 <body style="background-color:#efefef; border:0; margin:0; padding:10px 0 20px 0">
 mail content
 </body>
 </html>`;
```

When I use `renderHTML(mail);`, `font-size:12px` from the mail actually change the style of my whole app. Is there a way to stop this? Any guide will be helpful! Thanks

**Comment by noraesae** [comment]
If the html is inserted directly, the style is surely applied as global styles. To limit the effect of CSS, simply do not use the global style. Iframe may work, but I am not sure it works well with HTML email.

**Comment by Hongbo-Miao** [comment]
Thanks for help!
I found a way, hopefully this will help other people who have similar question.

Since I don't want to use iframe, I add this in my css, so the css in the mail does not have the effect.

```css
body {
  font-size: inherit !important;
  /* similar, you can add "line-height: inherit !important;", etc. */
}
```
