### ISSUE TITLE
Doesn't handle style attribute when string

### ISSUE THREAD

**Issue by Wildhoney** [noraesae/react-render-html#3]
> bundle.js?14647680834850354:5960 Uncaught (in promise) Error: The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.(…)

It occurs when you attempt to render a HTML string that contains a `style` attribute:

```javascript
{renderHTML(`<a style="text-transform: uppercase">GitHub.com</a>`)}
```

**Comment by noraesae** [comment]
PR merged. Thanks!
