### ISSUE TITLE
inline style with multiple attributes

### ISSUE THREAD

**Issue by daisyxu0924** [noraesae/react-render-html#9]
Hello, if you have inline style like: 
<div style="background-color: red; padding-left: 0"/> this won't be parsed correctly because the package react-styling is only handling styles with '\n' format.

So I can either work around by doing: 
`<div style="background-color: red\n padding-left: 0"/>` so it will parse background-color: red padding-left: 0 to `{background-color: red, padding-left: 0}`

Or, just write a simple JSON parser instead of using react-styling.

**Comment by noraesae** [comment]
Confirm the problem. Will work on this in a while!

**Comment by noraesae** [comment]
Fixed with [a new style parser](https://github.com/noraesae/react-render-html/blob/master/lib/style-parser.js). The fix is released under 0.1.6.

Thanks!
